version: '3.9'

services:
  db:
    image: postgres:15
    container_name: weepstay_postgres_db
    restart: always
    environment:
      POSTGRES_DB: weepstay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dulkar123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
